name: Generate README

on:
  push:
    branches:
      - master
  issues:
    types:
      - opened
      - edited
      - deleted

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Configure Git
        run: |
          git config --global user.email "karinavu.january@gmail.com"
          git config --global user.name "Karina's Bot"


      - name: Run script to generate README
        env:
          token: ${{ secrets.TOKEN }}
        run: |
          python main.py


      - name: Commit changed files
        run: |
          git add .
          git commit -m "Auto updating README.md"

      - name: Push to master
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git push origin HEAD:master
